apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "shoe"
  namespace: dev
  labels:
    app:  "shoe"
spec:
  selector:
    matchLabels:
      app: "shoe"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  "shoe"
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  "shoe"
        image:  deekshithsn/shoe
        ports:
        - containerPort: 1002
          name: "shoe"
---
apiVersion: v1
kind: Service
metadata:
  name: shoe
  namespace: dev
spec:
  selector:
    app: "shoe"
  type: ClusterIP
  - name: shoe
    port: 1002
    targetPort: 1002
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.