apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
   {{- include "offers-chart.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
    {{- include "offers-chart.selectorLabels" . | nindent 8 }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
      {{- include "offers-chart.selectorLabels" . | nindent 8 }}
    spec:
     containers:
      - name:  {{.Values.container.name }}
        image:  {{.Values.image.repository }}
        ports:
         - containerPort: {{.Values.service.targetPort }}
           name: {{ .Values.service.name }}