apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec:
 selector:
   {{- include "cart.selectorLabels" . | nindent 4}}
 type:  {{ .Values.service.type}}
 ports:
  - name: {{.Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{.Values.service.targetport }}