# Default values for shoe-cart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deekshithsn/shoe
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
service:
  type: ClusterIP
  port: 1002
  targetPort: 1002
  name: shoe
container:
  name: shoe


