apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "react-ui"
  namespace: dev
  labels:
    app:  "react-ui"
spec:
  selector:
    matchLabels:
      app: "react-ui"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "react-ui"
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
    containers:
      - name:  "react-ui"
        image:  deekshithsn/ui  
        ports:
        - containerPort:  80
          name:  "react-ui"
---        
      apiVersion: v1
      kind: Service
      metadata:
        name: "react-ui"
        namespace: dev
      spec:
        selector:
          app: "react-ui"
        type: NodePort
        ports:
        - name: "react-ui"
          port: 8080
          targetPort: 8080
          # If you set the `spec.type` field to `NodePort` and you want a specific port number,
          # you can specify a value in the `spec.ports[*].nodePort` field.
        