# Default values for wishlist.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: deekshithsn/wishlist
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 1003
  targetPort: 5000
  name: wishlist
container:
  name: wishlist

