apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "wishlist"
  namespace: dev
  labels:
    app:  "wishlist"
spec:
  selector:
    matchLabels:
      app: "wishlist"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  "wishlist"
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  "wishlist"
        image: deekshithsn/wishlist
        ports:
        - containerPort: 5000
          name:  "wishlist"
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist
  namespace: dev
spec:
  selector:
    app: "wishlist"
  type: ClusterIP
  ports:
  - name: wishlist
    port: 1003
    targetPort: 5000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,

