apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  labels:
    {{- include "ui-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "ui-helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount  }}
  template:
    metadata:
      labels:
        {{- include "ui-helm.selectorLabels" . | nindent 8 }}
  spec:
    containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository | quote  }}
          imagepullpolicy: {{ .Values.image.pullPolicy }}  
          ports:
          - containerPort: {{ .Values.service.targetport}}