apiVersion: "v1"
kind: "Service"
metadata:
  name: 
     {{ .Release.Name }} -service
  labels: 
         {{- include "ui-helm.labels" . | nindent 4 }}
spec:
 selector:
  {{- include "ui-helm.selectorLabels" . | nindent 4}}
 type: 
  {{ .Values.service.type | quote }}
 ports:
  - name: "http"
    port: {{  .Values.service.port  | quote }}
    targetPort: {{  .Values.service.targetport  | quote }}